dataset_id: hg68n
metrics_files: ???
target_metric_types:
  containers: True
  services: True
  nodes: True
  middlewares: True
upload_plots: false  # upload graph image to Neptune
neptune:
  mode: debug
time:
  num_datapoints: 120
  fault_inject_time_index: 99
labbeling:
  n_sigma_rule:
    n_sigmas: [2, 3]
