version: '3'

services:
  tsdr:
    build: .
    volumes:
      - .:/usr/src/app
    entrypoint: ["/usr/src/app/bin/tsdr_cli.py"]
  diag-cause:
    build: .
    volumes:
      - .:/usr/src/app
    entrypoint: ["/usr/src/app/bin/diag_cause_cli.py"]
  eval-tsdr:
    build: .
    volumes:
      - .:/usr/src/app
    entrypoint: ["/usr/src/app/tools/eval_tsdr.py"]
    env_file:
      - .env.local
  verify-metrics:
    build: .
    volumes:
      - .:/usr/src/app
    entrypoint: ["/usr/src/app/tools/verify_metrics.py"]
