version: '3'

services:
  eval-dataset:
    build: .
    volumes:
      - .:/usr/src/app
    entrypoint: ["/usr/src/app/eval/bin/eval_dataset.py"]
    env_file:
      - .env.local
  eval-tsdr:
    build: .
    volumes:
      - .:/usr/src/app
    entrypoint: ["/usr/src/app/eval/bin/eval_tsdr.py"]
    env_file:
      - .env.local
  eval-diagnoser:
    build: .
    volumes:
      - .:/usr/src/app
    entrypoint: ["/usr/src/app/eval/bin/eval_diagnoser.py"]
    env_file:
      - .env.local
