version: '3'

services:
  tsdr:
    build: .
    volumes:
      - .:/usr/src/app
    entrypoint: ["/usr/src/app/tsdr.py"]
  diag-cause:
    build: .
    volumes:
      - .:/usr/src/app
    entrypoint: ["/usr/src/app/diag_cause.py"]
