dataset_id: hg68n
metrics_files: ???
target_metric_types:
  containers: True
  services: True
  nodes: True
  middlewares: True
defaults:
  - _self_
  - step1: ar_based_ad
  - step2: hierarchy
upload_plots: false  # upload graph image to Neptune
neptune:
  mode: debug
time:
  num_datapoints: 120
  fault_inject_time_index: 99
labbeling:
  n_sigma_rule:
    n_sigmas: [2, 3]
disable_dataset_validation: False
enable_label_evaluation: False
